name: flutterflow_colorpicker_example
description: "Flutter project demonstrating the flutterflow_colorpicker package."
publish_to: 'none'

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutterflow_colorpicker:
    path: ..

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
